### ISSUE TITLE
Site unresponsive when logging mood

### ISSUE THREAD

**Issue by thisisjoshjones** [benji6/moodtracker#315] opened 2024-02-06 22:34 UTC
Yesterday for the first time I noticed the site becoming unresponsive each time I tried to log a mood, right when I click Save. Refreshing the page does not resolve the issue. Today I’m having the same issue, and I tried on iOS (Safari) and macOS (Chrome).

Thanks for the great app, it has done wonders for my mental health!

**Comment by benji6** [comment] 2024-02-07 14:04
@thisisjoshjones sorry about this and thank you for reporting the issue.

I can't see any immediately obvious problems looking through logs and error reporting and cannot reproduce the issue.

You say that refreshing the page does not resolve the issue - is the Home page now broken for you? Do any pages work? Are you able to share a screenshot? If you know how, are you also able to take any screenshots of the developer tools (console and network panel)? That could also be helpful in narrowing down what is going on

**Comment by thisisjoshjones** [comment] 2024-02-08 00:39
It seems every page breaks upon the first click of a button or toggle. I tried refreshing the same page and it becomes unresponsive.
![IMG_4686](https://github.com/benji6/moodtracker/assets/130625079/4cf41652-c5e4-43a3-b94c-ca6f0f9f97b5)
![IMG_4687](https://github.com/benji6/moodtracker/assets/130625079/c4d8fe8a-3bc3-4e7c-b8af-2644c2ce87bc)

here’s my attempt with the developer tools
<img width="1470" alt="Screenshot 2024-02-07 at 7 37 27 PM" src="https://github.com/benji6/moodtracker/assets/130625079/24cbb0ca-d3d7-4132-a5a9-b25c734ec224">

**Comment by benji6** [comment] 2024-02-08 22:29
I'm really stumped. I can see it appears to be stuck in a spinner state. This is supposed to be a temporary state while the app loads your locally stored data and your data from the cloud. The spinner should disappear as soon as that loading completes (either successfully or unsuccessfully).

One possibility is that the app is getting stuck in a loading state. I have made a change that will throw an error if the storage load hangs for more than 5 seconds (2c07b3eb84727d64108a3b1710220dff432e0a5f) and I've added error tracking if there is something going wrong while fetching data from the cloud (f1d2617c016f6a1f84d275b43b672a469d3abb8b). If you try again and wait 5 seconds do you see an error appear or anything different in the developer tools? 

Problem is that this would not explain how the issue arose or why you are seeing it on 2 separate devices. I assume you are using the latest version of Chrome on macOS? I also assume you were not trying to save some especially weird data (for instance something could go wrong if you were trying to save a colossal amount of data)?

I'll continue to investigate in the meantime

**Comment by thisisjoshjones** [comment] 2024-02-09 19:28
Thanks for all your work, this is an incredible amount of support considering this is a free and volunteer project.

Here's what I see now.
![IMG_4712](https://github.com/benji6/moodtracker/assets/130625079/d9fb9864-d036-4f26-a56a-7d93fcc46f69)

<img width="1470" alt="Screenshot 2024-02-09 at 2 19 18 PM" src="https://github.com/benji6/moodtracker/assets/130625079/33e8d70d-21f5-4c6c-ad62-bf6a9851431e">

**Comment by benji6** [comment] 2024-02-10 21:20
And thank you for your help in debugging this, it really bothers me that it isn't working for you!

So, we're still not seeing any errors which is unexpected. I have made another change which should display some text underneath the loading spinner to describe exactly what the app is doing. It will look like this:

<img width="148" alt="Screenshot 2024-02-10 at 21 12 56" src="https://github.com/benji6/moodtracker/assets/8782055/8044ba69-9993-42c7-9a61-d6e96d687099">

And should tell me exactly where your app is getting stuck if you share another screenshot.

I had another theory that maybe you aren't getting the latest version of the app, if you can screenshot the devtools again you should see a line that says something like `COMMIT_REF:  268507bf3295bb9289e4c26d8d9c5c80902a4e9e`. The exact text doesn't matter, but if you could share that with me it would validate that you are getting the latest version of the software. If you don't see that you probably won't see the text under the loading spinner either, but you can go to the about page https://moodtracker.link/about and find how long ago your version is from under the "Updates" header, for example:

<img width="582" alt="Screenshot 2024-02-10 at 21 16 24" src="https://github.com/benji6/moodtracker/assets/8782055/c1a652aa-1b4a-4082-9c09-f4db643f1da7">

This might take a couple more iterations to really nail down the issue, but I'm confident we can get it fixed. Thank you for your patience.

**Comment by thisisjoshjones** [comment] 2024-02-12 13:30
Here are my attempts to get that other info. COMMIT_REF is d9ea7484b86355f21104e42a0a9e36fc9cbb68ea, and the About page says the version was updated 1 day ago.

<img width="1470" alt="Screenshot 2024-02-12 at 8 27 43 AM" src="https://github.com/benji6/moodtracker/assets/130625079/60e9d795-3a37-4a66-8d08-c88428fa7a99">

<img width="1470" alt="Screenshot 2024-02-12 at 8 29 34 AM" src="https://github.com/benji6/moodtracker/assets/130625079/2218f31c-f41d-4ea3-8b54-82e784292c34">

**Comment by benji6** [comment] 2024-02-12 21:55
Thanks, very interesting. So you are getting the latest code version which is great. It looks like it spent 5 seconds trying to load storage before getting stuck on "Loading data from server"? I have another theory about what has happened.

Are you able to follow these instructions in Chrome https://www.howtogeek.com/664912/how-to-clear-storage-and-site-data-for-a-single-site-on-google-chrome?

One thing I'm particularly interested in is what that Usage section looks like, if you could take a screenshot and include the text (e.g. 197 KB out of 145494 MB storage quota) and the pie chart that would be great. Something like this:

![image](https://github.com/benji6/moodtracker/assets/8782055/2ca41adf-db22-4ebe-923e-a52c05350c1c)

If you follow the instructions and click the "Clear site data" button, then refresh the page and log in again is the issue fixed? 🙏

**Comment by thisisjoshjones** [comment] 2024-02-13 00:21
Here is that screenshot. This time it got stuck at "storage loading."
<img width="1470" alt="Screenshot 2024-02-12 at 7 17 10 PM" src="https://github.com/benji6/moodtracker/assets/130625079/2828f57f-3dfa-40f9-93d4-06ddc98801a9">

As soon as I cleared the data, the site immediately responded without even a refresh, showing me the logged-out home screen. But after I signed in, the site froze on the next screen (Check your device specific settings).
<img width="1470" alt="Screenshot 2024-02-12 at 7 18 00 PM" src="https://github.com/benji6/moodtracker/assets/130625079/e3cf0afb-5589-4e9b-82ee-12ea5439daaf">

I went back to get network and console for you, and the site had gone black.
<img width="1470" alt="Screenshot 2024-02-12 at 7 20 25 PM" src="https://github.com/benji6/moodtracker/assets/130625079/8a494595-8d5b-441d-a0f7-d67a61a79036">

**Comment by benji6** [comment] 2024-02-13 23:12
Thanks that's very helpful. My theory has been disproved. I have another idea but won't get round to testing it tonight. Will pick this up again in the next 24 hours or so

**Comment by benji6** [comment] 2024-02-14 16:12
I think it is fixed now.

There was a bug that only affected certain timezones which is why it appeared to be working normally. The app would get stuck in an infinite loop. Really tough one to spot and really appreciate your patience with this.

The fix is here 608c37238f5a8db2ac2d8c16e7e22f793639d4c8

Hopefully it is resolved now 🙏

**Comment by thisisjoshjones** [comment] 2024-02-14 23:25
It works now on both my devices! Thank you!!

**Comment by benji6** [comment] 2024-02-15 08:50
I'm very glad to hear it. Thanks for reporting the issue. If there's anything else I can do for you or any idea you have for MoodTracker please let me know :)

**Closed by benji6** 2024-02-15 08:50 UTC
